# Generated by Django 3.1.8 on 2021-05-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='user',
        ),
    ]
